### ISSUE TITLE
How can I use this project in container loading?

### ISSUE THREAD

**Issue by rlacjfjin** [Wadaboa/3d-bpp#5]
Hi,
If I want to use this project in container loading, 

for example,  I hvae 4 containers with (2280,2550,12000) size (width,height,length) , I want to loading 24 small boxes with some sizes and these boxes may be loaded 3 or 4 containers.

I found the "cg" and "bl" only support only one container loading, how can I solve such cases?

Thanks

**Comment by Wadaboa** [comment]
Hi, 

The easiest way would be to have some kind of heuristic to select a subset of remaining boxes to place in one of the containers. In this way, you could simply call the single-container optimization modules (e.g. `cg` or `bl`) to place the boxes you selected in the first container. Then, in the next iteration you select another subset of remaining boxes and apply the same reasoning, until all boxes are selected and all containers are loaded. 

Otherwise, if you want to do this in an optimal fashion, you need to come up with a 2-way optimization technique (i.e. optimizing box fitting and container loading together), which is not straightforward and definitely slower than the heuristic approach (if not implemented in the best way possible).

Let me know if you have other questions. Thanks,
Alessio.

**Comment by rlacjfjin** [comment]
As you mentioned in the first method, I get the result I want by controlling the filter_layers parameters of the min_density.
But the results were not ideal(In fact, the loading rate can reach about 90% but algorithm result can reach 75%), the initial idea is to improve the quality of the solution through local search(such as shuffling containers), but I can't sure it works well. 
Do you have any good suggestions?  
--------------
I have two questions in your generate super item method:
1. you call _drop_singles_in_horizontal function after call _gen_superitems_horizontal function, but there is no other operation after call _gen_superitems_vertical function, is it need to call such as _drop_singles_in_vertical function???
2. in FourHorizontalSuperitem, when calculating width and depth, should we only calculate the sum of the two items?
    But in your definition, it seems sum of four items as result.

Thanks,
Zhe
